language: java
jdk:
  - openjdk8
  
# whitelist
branches:
  only:
    - 3.10.x
    
script:
  - export BRANCH=/ecat3/test
  - mvn clean install -DskipTests -Penv-prod,es

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: $BRANCH
    