language: java
jdk:
  - openjdk8
  
# whitelist
branches:
  only:
    - 3.2.x
    - /^ecat3.2-.*$/ # any dev branch

script:
  - if [[ $TRAVIS_BRANCH =~ ^ecat3.2-.*$ ]];then
    export BRANCH=/ecat3/dev;
    else
    export BRANCH=/ecat3/prod;
    fi
  - mvn install -DskipTests=true

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: $BRANCH
    