sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
  - export MAVEN_OPTS="-Xmx512M -XX:MaxPermSize=256M"

# whitelist
branches:
  only:
    - prod
    - test
    - /^ecat3-.*$/ # any dev branch

script:
  - if [[ $TRAVIS_BRANCH =~ ^ecat3-.*$ ]];then
    export BRANCH="dev";
    else
    export BRANCH=$TRAVIS_BRANCH;
    fi
  - mvn install -DskipTests=true

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - ecat3/$TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: $BRANCH
    