site_name: GeoNetwork opensource
site_dir: target/html
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: suffix
      search_reconfigure: true
      material_alternate: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
      nav_translations:
        fr:
          Home: Home
          Search: Search
          Record: Record
          Map: Map

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - markdown_include.include:
      base_path: docs

extra:
  social:
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

nav:
  - 'Home': 'index.md'
  - 'Overview':
    - 'overview/index.md'
    - 'overview/about.md'
    - 'License':
      - 'overview/license/index.md'
      - 'overview/license/GPL.md'
    - 'overview/authors.md'
    - 'Changelog':
      - 'overview/change-log/index.md'
      - 'overview/change-log/version-4.2.5.md'
      - 'overview/change-log/version-3.12.9.md'
  - 'User Guide':
    - 'user-guide/index.md'
    - 'user-guide/quick-start/index.md'
  - 'Development':
    - 'devel/index.md'
    - 'devel/docs/docs.md'
