site_name: GeoNetwork opensource
site_dir: target/html
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: 'GeoNetwork (en)'
        - locale: fr
          name: Français
          build: true
          site_name: 'GeoNetwork (fr)'
          nav_translations:
            Home: Home
            Search: Search
            Record: Record
            Map: Map
  - exclude:
      glob:
        - 'overview/change-log/version*'
        - 'annexes/gallery/README.md'
        # in progress

  - include-markdown

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra:
  social:
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

nav:
  - 'Home':
    - 'index.md'
  - 'Overview':
    - 'overview/index.md'
    - 'overview/about.md'
    - 'License':
      - 'overview/license/index.md'
      - 'overview/license/GPL.md'
    - 'overview/authors.md'
    - 'Changelog':
      - 'overview/change-log/index.md'
      - 'overview/change-log/stable.md'
      - 'overview/change-log/maintenance.md'
      - 'overview/change-log/archive.md'
  - 'Install Guide':
      - install-guide/index.md
      - install-guide/installing-from-zip.md
      - install-guide/installing-from-war-file.md
      - install-guide/installing-with-docker.md
      - install-guide/installing-from-source-code.md
      - install-guide/installing-index.md
      - install-guide/configuring-database.md
      - install-guide/customizing-data-directory.md
      - install-guide/logging.md
      - install-guide/map-print-setup.md
      - install-guide/loading-samples.md
  - 'User Guide':
    - 'user-guide/index.md'
    - 'user-guide/quick-start/index.md'
  - 'Administrator Guide':
    - administrator-guide/index.md
    - 'Catalog':
      - administrator-guide/configuring-the-catalog/index.md
      - administrator-guide/configuring-the-catalog/system-configuration.md
      - administrator-guide/configuring-the-catalog/user-interface-configuration.md
      - administrator-guide/configuring-the-catalog/css-configuration.md
      - administrator-guide/configuring-the-catalog/csw-configuration.md
      - administrator-guide/configuring-the-catalog/portal-configuration.md
      - administrator-guide/configuring-the-catalog/inspire-configuration.md
      - administrator-guide/configuring-the-catalog/map-server-configuration.md
    - 'Users and Groups':
      - administrator-guide/managing-users-and-groups/index.md
      - administrator-guide/managing-users-and-groups/authentication-mode.md
      - administrator-guide/managing-users-and-groups/creating-group.md
      - administrator-guide/managing-users-and-groups/creating-user.md
      - administrator-guide/managing-users-and-groups/user-self-registration.md
    - 'Classification Systems':
      - administrator-guide/managing-classification-systems/index.md
      - administrator-guide/managing-classification-systems/managing-categories.md
      - administrator-guide/managing-classification-systems/managing-directories.md
      - administrator-guide/managing-classification-systems/managing-thesaurus.md
    - 'Metadata Standards':
      - administrator-guide/managing-metadata-standards/index.md
      - administrator-guide/managing-metadata-standards/configure-validation.md
      - administrator-guide/managing-metadata-standards/metadata-identifier.md
      - administrator-guide/managing-metadata-standards/standards.md
  - 'API':
    - 'api/index.md'
    - 'api/the-geonetwork-api.md'
    - 'api/search.md'
    - 'api/csw.md'
    - 'api/opensearch.md'
    - 'api/rdf-dcat.md'
    - 'api/oai-pmh.md'
    - 'api/z39-50.md'
  - 'Contributing':
    - contributing/index.md
    - contributing/writing-documentation.md
    - contributing/style-guide.md
    - contributing/translating.md
    - contributing/making-a-pull-request.md
    - contributing/doing-a-release.md
  - 'Customization':
    - customizing-application/index.md
    - 'Search':
      - customizing-application/search-ui/index.md
      - customizing-application/search-ui/configdefault.md
      - customizing-application/search-ui/customview.md
      - customizing-application/search-ui/enrichview.md
      - customizing-application/search-ui/loadview.md
      - customizing-application/search-ui/wro4jdependencies.md
    - customizing-application/creating-custom-view.md
    - customizing-application/editor-ui/creating-custom-editor.md
    - customizing-application/editor-ui/custom-editor-examples.md
    - customizing-application/editor-ui/tutorial.md
    - customizing-application/changing-layout.md
    - customizing-application/configuring-search-fields.md
    - customizing-application/configuring-faceted-search.md
    - customizing-application/advanced-configuration.md
    - customizing-application/adding-static-pages.md
    - customizing-application/characterset.md
    - customizing-application/implementing-a-schema-plugin.md
    - customizing-application/misc.md
  - 'Tutorials':
    - tutorials/index.md
    - 'Introduction':
       - tutorials/introduction/index.md
       - 'Overview':
         - tutorials/introduction/introduction/index.md
         - tutorials/introduction/introduction/discover.md
         - tutorials/introduction/introduction/map.md
         - tutorials/introduction/introduction/schema.md
         - 'Deployment':
           - tutorials/introduction/deployment/index.md
           - tutorials/introduction/deployment/build.md
           - tutorials/introduction/deployment/deploy.md
           - tutorials/introduction/deployment/docker.md
         - tutorials/introduction/setup/index.md
         - 'Edit':
           - tutorials/introduction/edit/index.md
           - tutorials/introduction/edit/edit.md
           - tutorials/introduction/edit/editor.md
         - tutorials/introduction/harvesting/index.md
         - tutorials/introduction/extra/index.md
    - 'Custom':
      - tutorials/customui/index.md
      - 'Search':
        - tutorials/customui/search/index.md
        - tutorials/customui/search/customview.md
        - tutorials/customui/search/defaultview.md
        - tutorials/customui/search/loadpage.md
      - 'View':
        - tutorials/customui/view/index.md
        - tutorials/customui/view/formatter.md
    - 'Hook':
      - tutorials/hookcustomizations/index.md
      - tutorials/hookcustomizations/events/index.md
      - tutorials/hookcustomizations/newproject/index.md
      - tutorials/hookcustomizations/schemaplugins/index.md
      - tutorials/hookcustomizations/searchfields/index.md
      - tutorials/hookcustomizations/ui/index.md
    - 'Inspire':
      - tutorials/inspire/index.md
      - tutorials/inspire/download-atom.md
      - tutorials/inspire/download-geoserver.md
      - tutorials/inspire/view-geoserver.md
      - tutorials/inspire/view-mapserver.md

  - 'Development':
    - 'devel/index.md'
    - 'devel/docs/docs.md'

