site_name: GeoNetwork opensource
site_dir: target/html
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: 'GeoNetwork (en)'
        - locale: fr
          name: Français
          build: true
          site_name: 'GeoNetwork (fr)'
          nav_translations:
            Home: Home
            Search: Search
            Record: Record
            Map: Map
  - exclude:
      glob:
        - 'overview/change-log/version*'
        - 'annexes/gallery/README.md'
        # in progress

  - include-markdown

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra:
  social:
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

nav:
  - 'Home':
    - 'index.md'
  - 'Overview':
    - 'overview/index.md'
    - 'overview/about.md'
    - 'License':
      - 'overview/license/index.md'
      - 'overview/license/GPL.md'
    - 'overview/authors.md'
    - 'Changelog':
      - 'overview/change-log/index.md'
      - 'overview/change-log/stable.md'
      - 'overview/change-log/maintenance.md'
      - 'overview/change-log/archive.md'
  - 'User Guide':
    - 'user-guide/index.md'
    - 'user-guide/quick-start/index.md'
  - 'Administrator Guide':
    - administrator-guide/index.md
    - 'Catalog':
      - administrator-guide/configuring-the-catalog/index.md
      - administrator-guide/configuring-the-catalog/system-configuration.md
      - administrator-guide/configuring-the-catalog/user-interface-configuration.md
      - administrator-guide/configuring-the-catalog/css-configuration.md
      - administrator-guide/configuring-the-catalog/csw-configuration.md
      - administrator-guide/configuring-the-catalog/portal-configuration.md
      - administrator-guide/configuring-the-catalog/inspire-configuration.md
      - administrator-guide/configuring-the-catalog/map-server-configuration.md
    - 'Users and Groups':
      - administrator-guide/managing-users-and-groups/index.md
      - administrator-guide/managing-users-and-groups/authentication-mode.md
      - administrator-guide/managing-users-and-groups/creating-group.md
      - administrator-guide/managing-users-and-groups/creating-user.md
      - administrator-guide/managing-users-and-groups/user-self-registration.md
    - 'Classification Systems':
      - administrator-guide/managing-classification-systems/index.md
      - administrator-guide/managing-classification-systems/managing-categories.md
      - administrator-guide/managing-classification-systems/managing-directories.md
      - administrator-guide/managing-classification-systems/managing-thesaurus.md
    - 'Metadata Standards':
      - administrator-guide/managing-metadata-standards/index.md
      - administrator-guide/managing-metadata-standards/configure-validation.md
      - administrator-guide/managing-metadata-standards/metadata-identifier.md
      - administrator-guide/managing-metadata-standards/standards.md
  - 'API':
    - 'api/index.md'
    - 'api/the-geonetwork-api.md'
    - 'api/search.md'
    - 'api/csw.md'
    - 'api/opensearch.md'
    - 'api/rdf-dcat.md'
    - 'api/oai-pmh.md'
    - 'api/z39-50.md'
  - 'Development':
    - 'devel/index.md'
    - 'devel/docs/docs.md'

