# Project information
site_name: GeoNetwork opensource
site description: >-
   GeoNetwork catalogue for listing, searching and reviewing records.
site_dir: target/html

# Repository
repo_name: geonetwork/core-geonetwork
repo_url: https://github.com/geocat/core-geonetwork
edit_uri: edit/mkdocs/docs/manual/docs

# Copyright
copyright: Copyright &copy; 2001 - 2023 FAO-UN and others


extra_css:
  - stylesheets/extra.css

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
#   - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
#   - navigation.footer
    - announce.dismiss

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: 'GeoNetwork Opensource (EN)'
        - locale: fr
          name: Français
          build: !ENV [FRENCH,false]
          site_name: 'GeoNetwork Opensource (FR)'
          nav_translations:
            Home: Home
            Search: Search
            Record: Record
            Map: Map
  - exclude:
      glob:
        - annexes/gallery/README.md
        - 'overview/change-log/version*'
  - include-markdown

# Customizations
extra:
  social:
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Page tree
nav:
  - index.md
  - 'Overview':
    - overview/index.md
    - overview/about.md
    - 'License':
      - overview/license/index.md
      - overview/license/GPL.md
    - overview/authors.md
    - 'Changelog':
      - overview/change-log/index.md
      - overview/change-log/stable.md
      - overview/change-log/maintenance.md
      - overview/change-log/archive.md
  - 'Installation Guide':
      - 'Installing':
        - install-guide/index.md
        - install-guide/installing-from-zip.md
        - install-guide/installing-from-war-file.md
        - install-guide/installing-with-docker.md
        - install-guide/installing-from-source-code.md
        - install-guide/installing-index.md
      - 'Configuration':
        - install-guide/configuring-database.md
        - install-guide/customizing-data-directory.md
        - install-guide/logging.md
        - install-guide/map-print-setup.md
        - install-guide/loading-samples.md
  - 'User Guide':
    - user-guide/index.md
    - user-guide/quick-start/index.md
    - user-guide/map/index.md
    - 'Describing Information':
      - user-guide/describing-information/index.md
      - user-guide/describing-information/creating-metadata.md
      - user-guide/describing-information/deleting-metadata.md
      - user-guide/describing-information/editing-metadata.md
      - user-guide/describing-information/importing-metadata.md
      - user-guide/describing-information/inspire-editing.md
      - user-guide/describing-information/managing-templates.md
      - user-guide/describing-information/multilingual-editing.md
    - 'Associating Resources':
      - user-guide/associating-resources/index.md
      - user-guide/associating-resources/cite.md
      - user-guide/associating-resources/doi.md
      - user-guide/associating-resources/linking-dataset-or-service.md
      - user-guide/associating-resources/linking-documents.md
      - user-guide/associating-resources/linking-feature-catalog.md
      - user-guide/associating-resources/linking-online-resources.md
      - user-guide/associating-resources/linking-others.md
      - user-guide/associating-resources/linking-parent.md
      - user-guide/associating-resources/linking-records.md
      - user-guide/associating-resources/linking-remote-records.md
      - user-guide/associating-resources/linking-source.md
      - user-guide/associating-resources/linking-thumbnail.md
      - user-guide/associating-resources/using-filestore.md
    - 'Tag information':
      - user-guide/tag-information/index.md
      - user-guide/tag-information/tagging-with-categories.md
      - user-guide/tag-information/tagging-with-keywords.md
    - 'Publishing':
      - user-guide/publishing/index.md
      - user-guide/publishing/managing-privileges.md
      - user-guide/publishing/restricting-information-to-metadata-sections.md
      - user-guide/publishing/transferring-privileges.md
    - 'Analyzing':
      - user-guide/analyzing/index.md
      - user-guide/analyzing/data.md
      - user-guide/analyzing/metadata.md
    - 'Workflow':
      - user-guide/workflow/index.md
      - user-guide/workflow/batchediting.md
      - user-guide/workflow/batchupdate-from-admin.md
      - user-guide/workflow/batchupdate-xsl.md
      - user-guide/workflow/batchupdate.md
      - user-guide/workflow/geopublication.md
      - user-guide/workflow/life-cycle.md
      - user-guide/workflow/suggestion.md
      - user-guide/workflow/validation.md
      - user-guide/workflow/versioning.md
    - 'Harvesting':
      - user-guide/harvesting/index.md
      - user-guide/harvesting/harvesting-csw.md
      - user-guide/harvesting/harvesting-filesystem.md
      - user-guide/harvesting/harvesting-geonetwork.md
      - user-guide/harvesting/harvesting-geoportal.md
      - user-guide/harvesting/harvesting-oaipmh.md
      - user-guide/harvesting/harvesting-ogcwxs.md
      - user-guide/harvesting/harvesting-sde.md
      - user-guide/harvesting/harvesting-simpleurl.md
      - user-guide/harvesting/harvesting-thredds.md
      - user-guide/harvesting/harvesting-webdav.md
      - user-guide/harvesting/harvesting-wfs-features.md
      - user-guide/harvesting/harvesting-z3950.md
    - user-guide/export/index.md
  - 'Administrator':
    - administrator-guide/index.md
    - 'Catalog':
      - administrator-guide/configuring-the-catalog/index.md
      - administrator-guide/configuring-the-catalog/system-configuration.md
      - administrator-guide/configuring-the-catalog/user-interface-configuration.md
      - administrator-guide/configuring-the-catalog/css-configuration.md
      - administrator-guide/configuring-the-catalog/csw-configuration.md
      - administrator-guide/configuring-the-catalog/portal-configuration.md
      - administrator-guide/configuring-the-catalog/inspire-configuration.md
      - administrator-guide/configuring-the-catalog/map-server-configuration.md
    - 'Users and Groups':
      - administrator-guide/managing-users-and-groups/index.md
      - administrator-guide/managing-users-and-groups/authentication-mode.md
      - administrator-guide/managing-users-and-groups/creating-group.md
      - administrator-guide/managing-users-and-groups/creating-user.md
      - administrator-guide/managing-users-and-groups/user-self-registration.md
    - 'Classification Systems':
      - administrator-guide/managing-classification-systems/index.md
      - administrator-guide/managing-classification-systems/managing-categories.md
      - administrator-guide/managing-classification-systems/managing-directories.md
      - administrator-guide/managing-classification-systems/managing-thesaurus.md
    - 'Metadata Standards':
      - administrator-guide/managing-metadata-standards/index.md
      - administrator-guide/managing-metadata-standards/configure-validation.md
      - administrator-guide/managing-metadata-standards/metadata-identifier.md
      - administrator-guide/managing-metadata-standards/standards.md
  - 'Maintainer':
      - maintainer-guide/index.md
      - 'Setting up search/content statistics':
        - maintainer-guide/statistics/index.md
        - maintainer-guide/statistics/setup-elasticsearch.md
        - maintainer-guide/statistics/setup-kibana.md
        - maintainer-guide/statistics/setup-geonetwork.md
      - 'Updating the application': maintainer-guide/updating/index.md
      - maintainer-guide/production-use/index.md
  - 'API':
    - api/index.md
    - api/the-geonetwork-api.md
    - api/search.md
    - api/csw.md
    - api/opensearch.md
    - api/rdf-dcat.md
    - api/oai-pmh.md
    - api/z39-50.md
  - 'Contributing':
    - contributing/index.md
    - 'Writing Documentation':
      - 'Markdown': devel/docs/docs.md
      - 'Sphinx - Deprecated': contributing/writing-documentation.md
    - contributing/style-guide.md
    - contributing/translating.md
    - contributing/making-a-pull-request.md
    - contributing/doing-a-release.md
  - 'Customization':
    - customizing-application/index.md
    - 'Search':
      - customizing-application/search-ui/index.md
      - customizing-application/search-ui/configdefault.md
      - customizing-application/search-ui/customview.md
      - customizing-application/search-ui/enrichview.md
      - customizing-application/search-ui/loadview.md
      - customizing-application/search-ui/wro4jdependencies.md
    - customizing-application/creating-custom-view.md
    - customizing-application/editor-ui/creating-custom-editor.md
    - customizing-application/editor-ui/custom-editor-examples.md
    - customizing-application/editor-ui/tutorial.md
    - customizing-application/changing-layout.md
    - customizing-application/configuring-search-fields.md
    - customizing-application/configuring-faceted-search.md
    - customizing-application/advanced-configuration.md
    - customizing-application/adding-static-pages.md
    - customizing-application/characterset.md
    - customizing-application/implementing-a-schema-plugin.md
    - customizing-application/misc.md
  - 'Tutorials':
    - tutorials/index.md
    - 'Introduction':
       - tutorials/introduction/index.md
       - 'Overview':
         - tutorials/introduction/introduction/index.md
         - tutorials/introduction/introduction/discover.md
         - tutorials/introduction/introduction/map.md
         - tutorials/introduction/introduction/schema.md
         - 'Deployment':
           - tutorials/introduction/deployment/index.md
           - tutorials/introduction/deployment/build.md
           - tutorials/introduction/deployment/deploy.md
           - tutorials/introduction/deployment/docker.md
         - tutorials/introduction/setup/index.md
         - 'Edit':
           - tutorials/introduction/edit/index.md
           - tutorials/introduction/edit/edit.md
           - tutorials/introduction/edit/editor.md
         - tutorials/introduction/harvesting/index.md
         - tutorials/introduction/extra/index.md
    - 'Customize':
      - tutorials/customui/index.md
      - 'Search':
        - tutorials/customui/search/index.md
        - tutorials/customui/search/customview.md
        - tutorials/customui/search/defaultview.md
        - tutorials/customui/search/loadpage.md
      - 'View':
        - tutorials/customui/view/index.md
        - tutorials/customui/view/formatter.md
    - 'Hook':
      - tutorials/hookcustomizations/index.md
      - tutorials/hookcustomizations/events/index.md
      - tutorials/hookcustomizations/newproject/index.md
      - tutorials/hookcustomizations/schemaplugins/index.md
      - tutorials/hookcustomizations/searchfields/index.md
      - tutorials/hookcustomizations/ui/index.md
    - 'Inspire':
      - tutorials/inspire/index.md
      - tutorials/inspire/download-atom.md
      - tutorials/inspire/download-geoserver.md
      - tutorials/inspire/view-geoserver.md
      - tutorials/inspire/view-mapserver.md
  - 'Annexes':
    - annexes/index.md
    - annexes/mef-format.md
    - annexes/gallery/gallery.md
    - annexes/glossary/index.md
    - 'Standards':
      - annexes/standards/index.md
      - annexes/standards/iso19115-3.2018.md
      - annexes/standards/iso19139.md
      - annexes/standards/iso19110.md
      - annexes/standards/dublin-core.md
  - 'Development':
    - devel/index.md
    - devel/docs/docs.md

