site_name: Catalogue Help
site_dir: target/html
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

plugins:
  - search
  - offline
  - i18n:
      default_language: en
      docs_structure: suffix
      search_reconfigure: true
      material_alternate: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
      nav_translations:
        fr:
          Home: Home
          Search: Search
          Record: Record
          Map: Map

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra:
  social:
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

nav:
  - 'index.md'
  - 'Home page':
    - 'home/index.md'
  - 'Search page':
    - 'search/index.md'
  - 'Detail page':
    - 'record/index.md'
  - 'Map':
    - 'map/index.md'
    - 'map/visualize/index.md'
  - 'Tags':
      - tags.md
