name: Docker image CI

on:
  push:
    branches:
      - 'metadata-indicators'
  pull_request:
    branches:
      - 'metadata-indicators'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'geocat/gn4-inspire-geoportal'

jobs:
  docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      -
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      -
        name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      -
        name: Maven repository caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      -
        name: Build with Maven
        run: mvn -B -V install -DskipTests=true -Dmaven.javadoc.skip=true -Pharvester-data-push
      -
        name: Remove SNAPSHOT jars from repository
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
      -
        name: Remove Schema 3.8 jars from repository
        run: |
          find ~/.m2/repository -name "*3.8*" -type d | xargs rm -rf {}
      -
        name: Copy WAR to target docker folder
        run: |
          mkdir -p docker/geocat/war
          cp web/target/geonetwork.war docker/geocat/war/


      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Transform GitHub Actions metadata to Docker image tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
          labels: |
            org.opencontainers.image.vendor=GeoCat B.V.
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=raw,,value={{branch}}-{{sha}}
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker/geocat/
          file: ./docker/geocat/DockerfileGeocat
          platforms: linux/amd64,linux/arm64
          build-args: |
            "DATA_DIR=/usr/local/live-geonetwork/data"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


